In [1]:
import sys
print(sys.executable)

/Users/shiva/AI_ED/llm_engineering/.venv/bin/python


In [2]:
vector = [0.2, -0.5, 0.8]

print("Vector:", vector)
print("Number of dimensions:", len(vector))

Vector: [0.2, -0.5, 0.8]
Number of dimensions: 3


In [3]:
embedding_1 = [0.2, 0.1, 0.7]
embedding_2 = [0.21, 0.12, 0.68]

print("Embedding 1 dimensions:", len(embedding_1))
print("Embedding 2 dimensions:", len(embedding_2))

Embedding 1 dimensions: 3
Embedding 2 dimensions: 3


In [4]:
import numpy as np

embeddings = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

print(embeddings)
print("Shape:", embeddings.shape)

[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]
Shape: (3, 4)


In [5]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

sentence = "Batman protects Gotham City."

embedding = model.encode(sentence)

print("Type:", type(embedding))
print("Shape:", embedding.shape)
print("First 10 values:", embedding[:10])

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Type: <class 'numpy.ndarray'>
Shape: (384,)
First 10 values: [ 0.03610526  0.11455762 -0.05047607  0.02178195  0.05463973  0.07952383
  0.04227993 -0.01485632 -0.07591661  0.04806218]


In [10]:
print("Number of NumPy axes:", embedding.ndim)
print("Shape:", embedding.shape)
print("Number of values:", len(embedding))
print("Data type:", embedding.dtype)

Number of NumPy axes: 1
Shape: (384,)
Number of values: 384
Data type: float32


In [11]:
sentences = [
    "Batman protects Gotham City.",
    "A superhero defends a city from criminals.",
    "A chef prepares pasta in an Italian restaurant."
]

embeddings = model.encode(sentences)

print("Type:", type(embeddings))
print("Number of NumPy axes:", embeddings.ndim)
print("Shape:", embeddings.shape)
print("Data type:", embeddings.dtype)

Type: <class 'numpy.ndarray'>
Number of NumPy axes: 2
Shape: (3, 384)
Data type: float32


In [12]:
print("Sentence 1:", sentences[0])
print("Embedding 1 shape:", embeddings[0].shape)

print("Sentence 2:", sentences[1])
print("Embedding 2 shape:", embeddings[1].shape)

print("Sentence 3:", sentences[2])
print("Embedding 3 shape:", embeddings[2].shape)

Sentence 1: Batman protects Gotham City.
Embedding 1 shape: (384,)
Sentence 2: A superhero defends a city from criminals.
Embedding 2 shape: (384,)
Sentence 3: A chef prepares pasta in an Italian restaurant.
Embedding 3 shape: (384,)


In [13]:
from sentence_transformers.util import cos_sim

similarity_0_1 = cos_sim(embeddings[0], embeddings[1])
similarity_0_2 = cos_sim(embeddings[0], embeddings[2])

print("Batman vs superhero:", similarity_0_1)
print("Batman vs chef:", similarity_0_2)

Batman vs superhero: tensor([[0.7290]])
Batman vs chef: tensor([[-0.0387]])


In [14]:
import numpy as np

A = np.array([2, 3])
B = np.array([4, 5])

dot_product = np.dot(A, B)

print("Dot product:", dot_product)

Dot product: 23


In [15]:
magnitude_A = np.linalg.norm(A)
magnitude_B = np.linalg.norm(B)

print("Magnitude of A:", magnitude_A)
print("Magnitude of B:", magnitude_B)

Magnitude of A: 3.605551275463989
Magnitude of B: 6.4031242374328485


In [16]:
cosine_similarity = dot_product / (magnitude_A * magnitude_B)

print("Cosine similarity:", cosine_similarity)

Cosine similarity: 0.9962405881956831


In [20]:
A = np.array([2.0, 3.0], dtype=np.float32)
B = np.array([4.0, 5.0], dtype=np.float32)

library_similarity = cos_sim(A, B)

print("Manual cosine similarity:", cosine_similarity)
print("Library cosine similarity:", library_similarity)

Manual cosine similarity: 0.9962405881956831
Library cosine similarity: tensor([[0.9962]])


In [21]:
batman = embeddings[0]
superhero = embeddings[1]
chef = embeddings[2]

batman_superhero_manual = np.dot(batman, superhero) / (
    np.linalg.norm(batman) * np.linalg.norm(superhero)
)

batman_chef_manual = np.dot(batman, chef) / (
    np.linalg.norm(batman) * np.linalg.norm(chef)
)

print("Batman vs superhero:", batman_superhero_manual)
print("Batman vs chef:", batman_chef_manual)

Batman vs superhero: 0.7290079
Batman vs chef: -0.038686924


Mini semantic search engine


In [22]:
movies = [
    "A masked superhero protects a dark city from dangerous criminals.",
    "A young lion must learn to become the king of his homeland.",
    "A chef travels across Italy learning traditional cooking techniques.",
    "A family of superheroes tries to balance ordinary life with saving the world.",
    "Two astronauts explore a mysterious planet far from Earth."
]

In [23]:
query = "fun superhero movie about a family"

In [26]:
import os

In [27]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

In [28]:
movies_embed = model.encode(movies)

In [29]:
query_embed = model.encode(query)

In [ ]:
print("movie embed shape",movies_embed.shape)
print("query embed shape",query_embed.shape)

# (5,384) in shape means , 5embed * 384 vectors..


movie embed shape (5, 384)
query embed shape (384,)


In [31]:
scores=cos_sim(query_embed,movies_embed)

In [32]:
print("Scores",scores)
print("Scores",scores.shape)

Scores tensor([[ 0.3963,  0.2295, -0.0147,  0.6937,  0.0738]])
Scores torch.Size([1, 5])


In [33]:
scores_1d=scores[0]
ranking=scores_1d.argsort(descending=True)

print("Ranking indices:",ranking)



Ranking indices: tensor([3, 0, 1, 4, 2])
